CREATE TABLE IF NOT EXISTS `PRODUCT`(
COMPANY_ID INT NOT NULL,
PRODUCT_ID INT PRIMARY KEY AUTO_INCREMENT,
PRODUCT_NAME VARCHAR(300) NOT NULL,
PRODUCT_IMAGE VARCHAR(300) NOT NULL UNIQUE,
PRICE INT NOT NULL,
FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(COMPANY_ID) on DELETE RESTRICT
)ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8;